from routes.auth import auth_bp
from routes.admin import admin_bp
from routes.hod import hod_bp
from routes.faculty import faculty_bp
from routes.student import student_bp
from routes.resume import resume_bp
from routes.notes import notes_bp
from routes.papers import papers_bp
from routes.outreach import outreach_bp
from routes.placements import placements_bp
from routes.chatbot import chatbot_bp
from routes.ppt import ppt_bp
